# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestPE54MT12():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testPE54MT12(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()

    # Primer intento
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("prueba@fail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("userfail123")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input").click()
    text = self.driver.find_element(By.TAG_NAME, "p").text  # Chequeo que el mensaje sea "Invalid UserId / Password"
    assert 'Invalid UserId / Password' == text

    # Segundo intento
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("prueba@fail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("userfail123")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input").click()
    text = self.driver.find_element(By.TAG_NAME, "p").text  # Chequeo que el mensaje sea "Invalid UserId / Password"
    assert 'Invalid UserId / Password' == text

    # Tercer intento
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("prueba@fail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("userfail123")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input").click()
    text = self.driver.find_element(By.TAG_NAME, "p").text  # Chequeo que el mensaje sea "Invalid UserId / Password"
    assert 'Invalid UserId / Password' == text

    # Cuarto intento
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("prueba@fail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("userfail123")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input").click()
    text = self.driver.find_element(By.TAG_NAME, "p").text  # Chequeo que el mensaje sea "Invalid UserId / Password"
    assert 'Your user has been blockled' == text
  
